---
title: "rmd file"
author: Selina Lyu
output: github_document
---
```{r, include = FALSE}
library(tidyverse)
library(rvest)
set.seed(1)



knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Lists

You can put anything in a list
```{r}
l = list (
vec_numeric = 5:8,
vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
mat = matrix(1:8, nrow = 2, ncol = 4),
summary = summary(rnorm(100))
)

l
l$vec_numeric
l[[1]]
l[[1]][1:3]
mean(l[["vec_numeric"]])
```

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

go back to old function

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply that function to each list element

```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a for loop:
```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## Let's try map

```{r}
output = map(list_norms, mean_and_sd)

output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = median(list_norms[[i]])
}

output = map(list_norms, median)
output = map(list_norms, IQR)
```

```{r}
output = map_dbl(list_norms, median, .id = "input")
```

```{r}
output = map_dfr(list_norms, mean_and_sd, .id = "input")
```

## list columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df |> pull(name)
listcol_df |> pull(samp)
pull(listcol_df, samp)[[1]]
mean_and_sd(pull(listcol_df, samp)[[1]])

map(pull(listcol_df, samp), mean_and_sd)
```

add a list column
```{r}
listcol_df = 
  listcol_df |> 
  mutate(summary = map(samp, mean_and_sd),
  medians = map_dbl(samp, median))

listcol_df
```

## Weather data

```{r}
library(p8105.datasets)
data("weather_df")
```

Get our list colums...

```{r}
weather_nest = 
  nest(weather_df, data = date:tmin)

weather_nest

weather_nest |> pull(name)
weather_nest |> pull(data)
```

Suppose I want to regress tmax on tmin for each station

```{r}
lm(tmax ~ tmin, data = weather_nest$data[[1]])
lm(tmax ~ tmin, data = weather_nest$data[[2]])
lm(tmax ~ tmin, data = weather_nest$data[[3]])
```

```{r}
weather_lm = function(df) {  #function of a dataframe...
  lm(tmax ~ tmin, data = df)
}

weather_lm(weather_nest$data[[1]])

output = vector("list", 3)

for (i in 1:3){
  output[[i]] = weather_lm(weather_nest$data[[i]])
}
```

What about a map?

```{r}
map(pull(weather_nest, data), weather_lm)

map(pull(weather_nest, data), \(df) lm(tmax ~ tmin, data = df))
```

map in a list column

```{r}
weather_nest = 
  weather_nest |> 
  mutate(models = map(data, weather_lm))

weather_nest

weather_nest$models
```

## NSDUH

```{r}
nsduh_table <- function(html, table_num) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
}
```

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

output = vector("list", 3)

for (i in c(1, 4, 5)) {
  output[[i]] = nsduh_table(nsduh_html, i)
}

nsduh_results = bind_rows(output)
```

```{r}
nsduh_results = 
  map(c(1, 4, 5), nsduh_table, html = nsduh_html) |> 
  bind_rows()
```

```{r}
nsduh_results= 
  tibble(
    name = c("marj", "cocaine", "heroine"),
    number = c(1, 4, 5)) |> 
  mutate(table = map(number, nsduh_table, html = nsduh_html)) |> 
  unnest(cols = "table")
```


































